spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/jian?useUnicode=true&characterEncoding=utf-8&useSSL=true
    username: root
    password: 521428
  redis:
    password: 521428Slyt
    port: 6379
    database: 0
    host: 118.24.38.46
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
    open-in-view: true
######thymeleaf######
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
    encoding: UTF-8
    servlet:
      content-type: text/html
    cache: false
######JWT认证配置######
jwt:
  header: Authorization
  secret: 521428Slyt
  #token七天不过期
  expiration: 604800
  tokenHead: "eyJhbGciOiJIUzUxMiJ9"
  exceptUrl: "/auth/**"
server:
  port: 8080